import { useRouter } from "next/router";
import React from "react";
import SideDrawer from "../components/navigation/SideDrawer";
import Fade from "@material-ui/core/Fade";
import { makeStyles } from "@material-ui/core/styles";
import Modal from "@material-ui/core/Modal";
import { IconButton, Box, Grid } from "@material-ui/core";
import HighlightOffIcon from "@material-ui/icons/HighlightOff";

import {
  getAllAgroPermaLabInfo,
  getAgroPermaLabInfoBySlug,
} from "../api/graphcms";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Label from "../components/Label";
import LabelNoLink from "../components/LabelNoLink";

export async function getStaticPaths() {
  const { infoPages } = await getAllAgroPermaLabInfo();
  var paths = [];
  for (var j = 0; j <= Object.keys(infoPages).length - 1; j++) {
    console.log(infoPages[j].slug);
    paths.push({
      params: {
        slug: infoPages[j].slug,
      },
    });
  }
  console.log(paths);
  return {
    paths: paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  console.log("Slugs:", params.slug);
  const infoPage = await getAgroPermaLabInfoBySlug(params.slug);
  const currentInfoPage = infoPage.infoPage;
  console.log("*****");

  return {
    props: {
      currentInfoPage,
    },
  };
}

export default function OpenArtifactPage({ currentInfoPage }) {
  React.useEffect(() => {
    // Prefetch the dashboard page
    router.prefetch("/");
  }, []);

  const router = useRouter();
  const { slug } = router.query;
  console.log(slug);

  return (
    <>
      <Fade in={true} timeout={500}>
        <>
          <Head>
            <title>Supermarket Museum</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <div className="frontPageBackground">
              <div className={styles.frontPageLabel}>
                <Label
                  header="ENTER THE SUPERMARKET MUSEUM"
                  author=""
                  onClick={() => {
                    handleTransition();
                  }}
                  style={{ backgroundColor: "red" }}
                  hideButton={true}
                />
              </div>
            </div>
            <div className={styles.centeredLabel}>
              <LabelNoLink
                slug={"one-of-all"}
                header={"ONE OF ALL"}
                author="Somebody"
                showButton={true}
                onClick={() => handleTransitionArtifact()}
              />
            </div>
            {console.log(currentInfoPage)}
          </main>
          <Modal open={true}>
            <>
              <>
                {currentInfoPage != null ? (
                  <>
                    <div className="modalCanvas">
                      <div className="closeIcon">
                        <IconButton onClick={() => router.push("/")}>
                          <HighlightOffIcon labelStyle={{ fontSize: "4rem" }} />
                        </IconButton>
                      </div>
                      <Box p={(2, 4)} className="modalBoxContainer">
                        <Grid item xs={12} md={12}>
                          <div className="modalContentAdjusted">
                            <h1 className="heading">{currentInfoPage.title}</h1>
                            <Grid container spacing={5}>
                              <Grid item xs={12} md={12} lg={12}>
                                <div
                                  className={"artifactDescription"}
                                  dangerouslySetInnerHTML={{
                                    __html: currentInfoPage.content.html,
                                  }}
                                ></div>
                              </Grid>
                            </Grid>

                            <Grid
                              container
                              spacing={5}
                              className={"technicalInformationContainer"}
                            >
                              <Grid item xs={12} md={12} lg={6}>
                                <div className={"technicalInformation"} />
                              </Grid>
                              <Grid item xs={12} md={12} lg={6}>
                                <div className={"technicalInformation"} />
                              </Grid>
                            </Grid>
                          </div>
                        </Grid>
                      </Box>
                    </div>
                  </>
                ) : null}
              </>
            </>
          </Modal>
        </>
      </Fade>
    </>
  );
}
