import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Label from "../components/Label";
import LabelNoLink from "../components/LabelNoLink";
import SideDrawer from "../components/navigation/SideDrawer";
import { getAllAgroPermaLabInfo } from "../api/graphcms";
import Tooltip from "@material-ui/core/Tooltip";
import TooltipLabel from "../components/maps/Labels/TooltipLabel";

export async function getStaticProps() {
  const { infoPages } = await getAllAgroPermaLabInfo();
  console.log("****");
  console.log(infoPages);

  return {
    props: { infoPages },
  };
}

export default function Home({ infoPages }) {
  console.log(infoPages);
  const [showTransition, setShowTransition] = React.useState(false);
  function timeout(delay) {
    return new Promise((res) => setTimeout(res, delay));
  }
  const router = useRouter();

  async function handleTransition() {
    setShowTransition(true);
    await timeout(1000);
    router.push("/choose");
  }

  async function handleTransitionArtifact() {
    setShowTransition(true);
    await timeout(1000);
    router.push("/museum/artifacts/one-of-all");
  }

  const showTooltip = (slug) => {
    setIsClicked(false);
  };

  const [isClicked, setIsClicked] = React.useState(false);

  return (
    <>
      <Head>
        <title>Supermarket Museum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="frontPageBackground">
          <SideDrawer infoPages={infoPages} currentPage={""} />
          <div className={styles.frontPageLabel}>
            <Label
              header="ENTER THE SUPERMARKET MUSEUM"
              author=""
              onClick={() => {
                handleTransition();
              }}
              style={{ backgroundColor: "red" }}
              hideButton={true}
            />
          </div>
        </div>
        <div className={styles.centeredLabel}>
          <TooltipLabel
            artifactTitle={"One Of All"}
            artifactSlug={"one-of-all"}
            artifactAuthor={"Clemens Büntig"}
            isClicked={isClicked}
            showTooltip={showTooltip}
            handleShow={handleTransitionArtifact}
            xLocation={"44.2%"}
            yLocation={"49.6%"}
          />
        </div>
      </main>
      <div className={showTransition ? styles.transitionOpening : ""}>
        <div className={styles.bgLayer}></div>
      </div>
    </>
  );
}
