import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Label from "../components/Label";
import LabelNoLink from "../components/LabelNoLink";

export default function Home() {
  const [showTransition, setShowTransition] = React.useState(false);
  function timeout(delay) {
    return new Promise((res) => setTimeout(res, delay));
  }
  const router = useRouter();

  async function handleTransition() {
    setShowTransition(true);
    await timeout(1000);
    router.push("/choose");
  }

  async function handleTransitionArtifact() {
    setShowTransition(true);
    await timeout(1000);
    router.push("/museum/artifacts/one-of-all");
  }

  return (
    <>
      <Head>
        <title>Supermarket Museum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="frontPageBackground">
          <div className={styles.frontPageLabel}>
            <Label
              header="ENTER THE SUPERMARKET MUSEUM"
              author=""
              onClick={() => {
                handleTransition();
              }}
              style={{ backgroundColor: "red" }}
              hideButton={true}
            />
          </div>
        </div>
        <div className={styles.centeredLabel}>
          <LabelNoLink
            slug={"one-of-all"}
            header={"ONE OF ALL"}
            author="Somebody"
            showButton={true}
            onClick={() => handleTransitionArtifact()}
          />
        </div>
      </main>
      <div className={showTransition ? styles.transitionOpening : ""}>
        <div className={styles.bgLayer}></div>
      </div>
    </>
  );
}
