import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Label from "../components/Label";
import LabelNoLink from "../components/LabelNoLink";

export default function Home() {
  const [showTransition, setShowTransition] = React.useState(false);
  function timeout(delay) {
    return new Promise((res) => setTimeout(res, delay));
  }
  const router = useRouter();

  async function handleTransition() {
    setShowTransition(true);
    await timeout(1000);
    router.push("/museum");
  }
  return (
    <>
      <Head>
        <title>Supermarket Museum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="frontPageBackground">
          <div className={styles.frontPageLabel}>
            <Label
              header="witam"
              author="siemanko"
              onClick={() => {
                handleTransition();
              }}
            />
          </div>
        </div>
      </main>
      <div className={showTransition ? styles.transitionOpening : ""}>
        <div className={styles.bgLayer}></div>
      </div>
    </>
  );
}
